spring:
  application:
    name: control-plane-service

  datasource:
    url: jdbc:postgresql://localhost:55432/forge
    username: forge
    password: forge_local_password

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      properties:
        enable.idempotence: true
        acks: all
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

server:
  port: 8081

logging:
  level:
    com.forge.controlplane: INFO